custom-shader =
cursor-color =
background-opacity = 1
background-opacity-cells = false
background-blur = false
background-image =
background-image-opacity = 1
background-image-fit = contain
background-image-position = center
background-image-repeat = false
