custom-shader =
background = #000000
background-opacity = 0.5
background-opacity-cells = true
background-blur = 0
background-image = /Users/antonhristov/Documents/my-vim-env/ghostty/images/Ghostty_background.jpg
background-image-opacity = 2
background-image-fit = cover
background-image-position = center
background-image-repeat = false
