if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
	git
	# zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="$PATH:/opt/nvim/"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
[ -f ~/.bashrc ] && source ~/.bashrc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


alias bat="batcat"
# alias yt = 'ytfzf -t'

alias inv='nvim $(fzf -m --preview="batcat --color=always {}")'

nvim() {
  case "$1" in
    zsh) command nvim ~/.zshrc ;;
    tmux) command nvim ~/.tmux.conf ;;
    *) command nvim "$@" ;;
  esac
}


vi() {
  nvim "$@" && clear
}

cls() {
  clear && ls
}
makc() {
  make && ls
}
alias cdu='cd ../'
alias c='clear'

source() {
  if [[ "$1" == "zsh" ]]; then
    builtin source ~/.zshrc
    echo "Sourced ~/.zshrc"
  elif [[ "$1" == "tmux" ]]; then
    tmux source-file ~/.tmux.conf
    echo "Sourced ~/.tmux.conf"
  else
    builtin source "$@"
  fi
}

alias lgit='lazygit'
alias ldocker='lazydocker'

eval "$(zoxide init --cmd cd zsh)"

alias rpi-tmux='tmux new-window "ssh -t toni@192.168.100.193 tmux attach-session -t default"'


# Automatically start tmux and run tmux-resurrect if not already in tmux
if [[ -z "$TMUX" ]]; then
    tmux new-session \; run-shell "~/.tmux/plugins/tmux-resurrect/scripts/restore.sh"
fi

eval $(thefuck --alias)
eval $(thefuck --alias fk)

# Setup auto install todo:
# 1. Install zsh
# 2. Install oh-my-zsh
# 3. Install powerlevel10k
# 4. Install zsh-autosuggestions
# 5. Install zsh-syntax-highlighting
# 6. Install fzf
# 7. Install bat
# 8. Install tmux
# 9. Install tmux-resurrect
# 10. Install tmux-continuum
# 11. Install zoxide
# 12. Install nvim
# 13. Install sdkman
# 15. Install lazygit
# 16. Install lazydocker
# 17. Install thefuck
# 18. Install yazi
# 19. Install glow - https://github.com/charmbracelet/glow

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

cheat() {
  # Ensure at least one argument (the language) is given
  if (( $# < 1 )); then
    echo "Usage: cheat <language> <query words> [ ?Q ]"
    return 1
  fi

  local lang=$1
  shift

  # Join the remaining arguments with plus signs.
  local query
  query=$(IFS=+; echo "$*")

  # Build the URL; note that if no query is provided, this will simply show the cheat sheet for the language.
  local url="cht.sh/${lang}/${query}"

  # Call curl to fetch the cheat sheet.
  curl "$url"
}

mancheat() {
  # Ensure at least one argument (the language) is given
  if (( $# < 1 )); then
    echo "Usage: cheat <language> <query words> [ ?Q ]"
    return 1
  fi

  local lang=$1
  shift

  # Join the remaining arguments with plus signs.
  local query
  query=$(IFS=+; echo "$*")

  # Build the URL; note that if no query is provided, this will simply show the cheat sheet for the language.
  local url="cht.sh/${lang}/${query}"

  # Call curl to fetch the cheat sheet.
  curl "$url" | less
}

